#!/usr/bin/env python2

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('gist')
parser.add_argument('name')
args = parser.parse_args()

from urllib2 import urlopen
import json

gist = args.gist
data = urlopen("https://api.github.com/gists/" + gist)
data = json.load(data)
name = args.name

with open(name + ".gist", "w") as f:
	f.write(json.dumps(data, sort_keys = True, indent=2))

with open(name + ".o8", "w") as f:
	f.write(data['files']['prog.ch8']['content'].encode('utf-8'))

options = json.loads(data['files']['options.json']['content'])
with open(name + ".options", "w") as f:
	f.write(json.dumps(options, sort_keys = True, indent=2))

qnames = ["shiftQuirks", "loadStoreQuirks", "vfOrderQuirks", "clipQuirks", "jumpQuirks"]
quirks = []
for k in qnames:
	if k in options:
		if options[k]:
			quirks.append("%s = on" %(name[:-6].lower()))

if quirks:
	options['quirks'] = "\n[quirks]\n" + "\n".join(quirks) + "\n"
else:
	options['quirks'] = ""

cnames = (
	('backgroundColor', 'bg'),
	('fillColor', 'color1'),
	('fillColor2', 'color2'),
	('blendColor', 'blend'),
	('buzzColor', 'buzzer'),
	('quietColor', 'border')
)
palette = []

for k, v in cnames:
	if k in options:
		palette.append("%-7s= %s" %(v, options[k]))
options['palette'] = '\n'.join(palette)

with open(name + ".ini", "w") as f:
	f.write(\
"""[core]
speed = {tickrate}
{quirks}
[palette]
{palette}
""" \
.format(**options))
